apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
enableServer: false
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
podCIDR: 10.241.1.0/24
staticPodPath: /etc/kubernetes/manifests
cgroupDriver: systemd
cgroupRoot: /kubelet
