name: For each commit and PR
on:
  push:
  pull_request:
jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Init
      run: sudo apt-get update && sudo apt-get install -y build-essential golint
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
    - name: checks
      run: make check
    - name: test docker build (with iptables)
      run: make dockerx86ActionIPTables
    - name: e2e services
      run: DOCKERTAG=action make service-tests
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'plndr/kube-vip:action'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
